### ISSUE TITLE
DNS settings for the mailinglist

### ISSUE THREAD

**Issue by Emzy** [bisq-network/dns#3]
Hello,

the IP-Addresses of the new malinglist server are:
51.15.92.183 and 2001:bc8:4700:2500::1e61

DNS Settings:
lists IN MX 50 lists.bisq.network.
lists IN A  51.15.92.183
lists IN AAAA 2001:bc8:4700:2500::1e61

Best.

update (@cbeams): reference bisq-network/lists#1

**Comment by cbeams** [comment]
Closing as complete. You should be good to go now, @Emzy, thanks!

![image](https://user-images.githubusercontent.com/301810/32134478-82f3e970-bbee-11e7-8923-32a6f2d2e020.png)
